<?php
    require("diettypes.php");
    require("feedback.php");
    require("follows.php");
    require("ingredients_diettypes.php");
    require("ingredients.php");
    require("measures.php");
    require("recipes_ingredients.php");
    require("recipes.php");
    require("reports.php");
    require("requests.php");
    require("user_ingredients.php");
    require("users.php");
?>